/**
 *
 *  MovementHistory.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace cms_simulator_db
{

class MovementHistory
{
  public:
    struct Cols
    {
        static const std::string _time;
        static const std::string _simulator_id;
        static const std::string _session_id;
        static const std::string _object_id;
        static const std::string _latitude_bearing;
        static const std::string _longitude_range;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = void;
    int getPrimaryKey() const { assert(false); return 0; }

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit MovementHistory(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit MovementHistory(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    MovementHistory(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    MovementHistory() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column time  */
    ///Get the value of the column time, returns the default value if the column is null
    const ::trantor::Date &getValueOfTime() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getTime() const noexcept;
    ///Set the value of the column time
    void setTime(const ::trantor::Date &pTime) noexcept;

    /**  For column simulator_id  */
    ///Get the value of the column simulator_id, returns the default value if the column is null
    const int32_t &getValueOfSimulatorId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getSimulatorId() const noexcept;
    ///Set the value of the column simulator_id
    void setSimulatorId(const int32_t &pSimulatorId) noexcept;

    /**  For column session_id  */
    ///Get the value of the column session_id, returns the default value if the column is null
    const int32_t &getValueOfSessionId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getSessionId() const noexcept;
    ///Set the value of the column session_id
    void setSessionId(const int32_t &pSessionId) noexcept;

    /**  For column object_id  */
    ///Get the value of the column object_id, returns the default value if the column is null
    const int32_t &getValueOfObjectId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getObjectId() const noexcept;
    ///Set the value of the column object_id
    void setObjectId(const int32_t &pObjectId) noexcept;

    /**  For column latitude_bearing  */
    ///Get the value of the column latitude_bearing, returns the default value if the column is null
    const double &getValueOfLatitudeBearing() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<double> &getLatitudeBearing() const noexcept;
    ///Set the value of the column latitude_bearing
    void setLatitudeBearing(const double &pLatitudeBearing) noexcept;

    /**  For column longitude_range  */
    ///Get the value of the column longitude_range, returns the default value if the column is null
    const double &getValueOfLongitudeRange() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<double> &getLongitudeRange() const noexcept;
    ///Set the value of the column longitude_range
    void setLongitudeRange(const double &pLongitudeRange) noexcept;


    static size_t getColumnNumber() noexcept {  return 6;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend drogon::orm::Mapper<MovementHistory>;
    friend drogon::orm::BaseBuilder<MovementHistory, true, true>;
    friend drogon::orm::BaseBuilder<MovementHistory, true, false>;
    friend drogon::orm::BaseBuilder<MovementHistory, false, true>;
    friend drogon::orm::BaseBuilder<MovementHistory, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<MovementHistory>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<::trantor::Date> time_;
    std::shared_ptr<int32_t> simulatorId_;
    std::shared_ptr<int32_t> sessionId_;
    std::shared_ptr<int32_t> objectId_;
    std::shared_ptr<double> latitudeBearing_;
    std::shared_ptr<double> longitudeRange_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[6]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
        sql += "time,";
        ++parametersCount;
        if(!dirtyFlag_[0])
        {
            needSelection=true;
        }
        if(dirtyFlag_[1])
        {
            sql += "simulator_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "session_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "object_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "latitude_bearing,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "longitude_range,";
            ++parametersCount;
        }
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        int placeholder=1;
        char placeholderStr[64];
        size_t n=0;
        if(dirtyFlag_[0])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[1])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[2])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[3])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[4])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[5])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        if(needSelection)
        {
            sql.append(") returning *");
        }
        else
        {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace cms_simulator_db
} // namespace drogon_model
